Repository neo4j/docs-ops-manager, pull requests merged in 2023-09, with the labels that each got.

#150 update version (#149)
  antora.yml
  preview.yml
  publish.yml
Labels: cherry-picked

#151 Describe requirements on db.logs.query.annotation_data_* configuration settings
  modules/ROOT/pages/addition/instance-requirements.adoc
Labels: cherry-pick-to-1.8

#153 Describe requirements on db.logs.query.annotation_data_* configuratio…
  modules/ROOT/pages/addition/instance-requirements.adoc
Labels: cherry-picked

#154 edit 155
  modules/ROOT/pages/addition/instance-requirements.adoc
Labels: documentation, cherry-pick-to-1.8

#152 fixes as proposed in the card
  modules/ROOT/pages/introduction/overview.adoc
Labels: cherry-pick-to-1.5, cherry-pick-to-1.6, cherry-pick-to-1.7, cherry-pick-to-1.8

#147 Replace java based self-signed certificate generation with OpenSSL
  modules/ROOT/pages/addition/agent-installation/agent-self-signed-certificates.adoc
  modules/ROOT/pages/first-look/docker-first-look.adoc
  modules/ROOT/pages/first-look/linux-first-look.adoc
  modules/ROOT/pages/installation/self-signed-certificate.adoc
Labels: cherry-pick-to-1.7, cherry-pick-to-1.8

#157 Replace java based self-signed certificate generation with OpenSSL (#…
  modules/ROOT/pages/addition/agent-installation/agent-self-signed-certificates.adoc
  modules/ROOT/pages/first-look/docker-first-look.adoc
  modules/ROOT/pages/first-look/linux-first-look.adoc
  modules/ROOT/pages/installation/self-signed-certificate.adoc
Labels: cherry-picked

#159 fix version
  publish.yml
Labels: documentation, do-not-cherry-pick

#160 Shorter title for better SEO (#148)
  modules/ROOT/pages/addition/docker/container.adoc
Labels: cherry-picked

#161 Shorter title for better SEO (#148)
  modules/ROOT/pages/addition/docker/container.adoc
Labels: cherry-picked

#145 :recycle: restructure addition docs
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/addition/agent-installation/agent-install.adoc
  modules/ROOT/pages/addition/agent-installation/index.adoc
  modules/ROOT/pages/addition/agent-installation/install-packaged.adoc
  modules/ROOT/pages/addition/agent-installation/manual.adoc
  modules/ROOT/pages/addition/agent-installation/self-registered.adoc
  modules/ROOT/pages/addition/docker/index.adoc
  modules/ROOT/pages/addition/instance-requirements.adoc
  modules/ROOT/pages/addition/kubernetes/daemonset.adoc
  modules/ROOT/pages/addition/kubernetes/sidecar.adoc
  modules/ROOT/pages/monitoring/log-manager.adoc
Labels: cherry-pick-to-1.7, cherry-pick-to-1.8

#162 :recycle: restructure addition docs (#145)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/addition/agent-installation/agent-install.adoc
  modules/ROOT/pages/addition/agent-installation/index.adoc
  modules/ROOT/pages/addition/agent-installation/install-packaged.adoc
  modules/ROOT/pages/addition/agent-installation/manual.adoc
  modules/ROOT/pages/addition/agent-installation/self-registered.adoc
  modules/ROOT/pages/addition/docker/index.adoc
  modules/ROOT/pages/addition/instance-requirements.adoc
  modules/ROOT/pages/addition/kubernetes/daemonset.adoc
  modules/ROOT/pages/addition/kubernetes/sidecar.adoc
  modules/ROOT/pages/monitoring/log-manager.adoc
Labels: cherry-picked

#158 Docker first look with openssl, mTLS and agent self registration
  modules/ROOT/pages/addition/agent-installation/agent-self-signed-certificates.adoc
  modules/ROOT/pages/addition/docker/compose.adoc
  modules/ROOT/pages/addition/docker/container.adoc
  modules/ROOT/pages/addition/kubernetes/sidecar.adoc
  modules/ROOT/pages/first-look/docker-first-look.adoc
  modules/ROOT/pages/first-look/linux-first-look.adoc
  modules/ROOT/pages/installation/docker/compose.adoc
  modules/ROOT/pages/installation/docker/container.adoc
  modules/ROOT/pages/installation/kubernetes/helm-charts.adoc
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-pick-to-1.7, cherry-pick-to-1.8

#167 Docker first look with openssl, mTLS and agent self registration (#158)
  modules/ROOT/pages/addition/agent-installation/agent-self-signed-certificates.adoc
  modules/ROOT/pages/addition/docker/compose.adoc
  modules/ROOT/pages/addition/docker/container.adoc
  modules/ROOT/pages/addition/kubernetes/sidecar.adoc
  modules/ROOT/pages/first-look/docker-first-look.adoc
  modules/ROOT/pages/first-look/linux-first-look.adoc
  modules/ROOT/pages/installation/docker/compose.adoc
  modules/ROOT/pages/installation/docker/container.adoc
  modules/ROOT/pages/installation/kubernetes/helm-charts.adoc
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-picked

#146 Update compatibility matrix
  modules/ROOT/pages/appendix/version-compatibility.adoc
Labels: cherry-pick-to-1.7, cherry-pick-to-1.8

#168 Docker first look with openssl, mTLS and agent self registration (#158)
  modules/ROOT/pages/addition/agent-installation/agent-self-signed-certificates.adoc
  modules/ROOT/pages/addition/docker/compose.adoc
  modules/ROOT/pages/addition/docker/container.adoc
  modules/ROOT/pages/addition/kubernetes/sidecar.adoc
  modules/ROOT/pages/first-look/docker-first-look.adoc
  modules/ROOT/pages/first-look/linux-first-look.adoc
  modules/ROOT/pages/installation/docker/compose.adoc
  modules/ROOT/pages/installation/docker/container.adoc
  modules/ROOT/pages/installation/kubernetes/helm-charts.adoc
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-picked

#169 Update compatibility matrix (#146)
  modules/ROOT/pages/appendix/version-compatibility.adoc
Labels: cherry-picked

#170 Update compatibility matrix (#146)
  modules/ROOT/pages/appendix/version-compatibility.adoc
Labels: cherry-picked

#171 fix version
  publish.yml
Labels: do-not-cherry-pick
