Repository neo4j/docs-ops-manager, pull requests merged in 2023-03, with the labels that each got.

#81 Require db.logs.query.enabled for log collection to work
  modules/ROOT/pages/addition/index.adoc
  modules/ROOT/pages/addition/instance-requirements.adoc
  modules/ROOT/pages/installation/kubernetes/helm-charts.adoc
Labels: cherry-pick-to-1.3, cherry-pick-to-1.4

#84 Require db.logs.query.enabled for log collection to work (#81)
  modules/ROOT/pages/addition/index.adoc
  modules/ROOT/pages/kubernetes/helm-charts.adoc
Labels: cherry-picked

#85 Require db.logs.query.enabled for log collection to work (#81)
  modules/ROOT/pages/addition/index.adoc
  modules/ROOT/pages/kubernetes/helm-charts.adoc
Labels: cherry-picked

#82 Add note on upgrade paths for NOM
  modules/ROOT/pages/appendix/version-compatibility.adoc
  modules/ROOT/pages/update/index.adoc
  modules/ROOT/pages/update/server.adoc
Labels: cherry-pick-to-1.1, cherry-pick-to-1.2, cherry-pick-to-1.3, cherry-pick-to-1.4

#86 Add note on upgrade paths for NOM (#82)
  modules/ROOT/pages/appendix/version-compatibility.adoc
  modules/ROOT/pages/upgrade/index.adoc
Labels: cherry-picked

#87 Add note on upgrade paths for NOM (#82)
  modules/ROOT/pages/appendix/version-compatibility.adoc
  modules/ROOT/pages/upgrade/index.adoc
Labels: cherry-picked

#88 1.2
  modules/ROOT/pages/appendix/version-compatibility.adoc
  modules/ROOT/pages/upgrade/index.adoc
Labels: cherry-picked

#89 1.1 (#88)
  modules/ROOT/pages/appendix/version-compatibility.adoc
  modules/ROOT/pages/upgrade/index.adoc
Labels: cherry-picked

#90 Query log setup
  modules/ROOT/pages/addition/index.adoc
  modules/ROOT/pages/addition/instance-requirements.adoc
  modules/ROOT/pages/monitoring/log-manager.adoc
Labels: cherry-pick-to-1.3, cherry-pick-to-1.4

#92 Cherry pick query log additions to 1.4
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/addition/index.adoc
  modules/ROOT/pages/addition/instance-requirements.adoc
  modules/ROOT/pages/monitoring/log-manager.adoc
Labels: cherry-picked

#93 Cherry pick query log additions to 1.3
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/addition/index.adoc
  modules/ROOT/pages/addition/instance-requirements.adoc
  modules/ROOT/pages/monitoring/log-manager.adoc
Labels: cherry-picked
