Repository neo4j/docs-ops-manager, pull requests merged in 2023-08, with the labels that each got.

#140 new ui bundle url
  preview.yml
  publish.yml
Labels: cherry-pick-to-1.7

#141 Add GHA
  .github/workflows/docs-deploy-surge.yml
  .github/workflows/docs-pr.yml
  .github/workflows/docs-teardown.yml
Labels: cherry-pick-to-1.7

#142 Add GHA (#141)
  .github/workflows/docs-deploy-surge.yml
  .github/workflows/docs-pr.yml
  .github/workflows/docs-teardown.yml
Labels: cherry-picked

#144 Add a note for SELinux to change the SELinux context of the server and agent binaries
  modules/ROOT/pages/addition/agent-installation/manual.adoc
  modules/ROOT/pages/addition/agent-installation/self-registered.adoc
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-pick-to-1.1, cherry-pick-to-1.2, cherry-pick-to-1.3, cherry-pick-to-1.4, cherry-pick-to-1.5, cherry-pick-to-1.6, cherry-pick-to-1.7
