Repository neo4j/docs-ops-manager, pull requests merged in 2023-07, with the labels that each got.

#126 Add a note about not using the operator role for the NOM persistence …
  modules/ROOT/pages/addition/instance-requirements.adoc
Labels: cherry-picked

#127 Add a note about not using the operator role for the NOM persistence …
  modules/ROOT/pages/addition/instance-requirements.adoc
Labels: cherry-picked

#128 Add a note about not using the operator role for the NOM persistence
  modules/ROOT/pages/addition/instance-requirements.adoc
Labels: cherry-picked

#124 Certificate file names and minor fixes
  modules/ROOT/pages/first-look/linux-first-look.adoc
  modules/ROOT/pages/installation/self-signed-certificate.adoc
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-pick-to-1.4, cherry-pick-to-1.5, cherry-pick-to-1.6

#129 Certificate file names and minor fixes (#124)
  modules/ROOT/pages/first-look/linux-first-look.adoc
  modules/ROOT/pages/installation/self-signed-certificate.adoc
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-picked

#130 Certificate file names and minor fixes (#124)
  modules/ROOT/pages/first-look/linux-first-look.adoc
  modules/ROOT/pages/installation/self-signed-certificate.adoc
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-picked

#132 fix typos
  modules/ROOT/pages/installation/docker/container.adoc
Labels: cherry-pick-to-1.6

#136 update version to 1.7
  antora.yml
  preview.yml
  publish.yml
Labels: documentation

#137 update version to 1.7 (#136)
  antora.yml
  preview.yml
  publish.yml
Labels: documentation

#138 Helm chart docs secretsFromSecrets update
  modules/ROOT/pages/installation/kubernetes/helm-charts.adoc
Labels: cherry-pick-to-1.7
