Repository neo4j/docs-ops-manager, pull requests merged in 2023-05, with the labels that each got.

#109 remove Neo4j namespaces setting
  modules/ROOT/pages/addition/instance-requirements.adoc
Labels: cherry-pick-to-1.6

#110 Document alerts and notifications for NOM 1.6 (#106)
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/alerts-panel.png
  modules/ROOT/images/alerts.png
  modules/ROOT/images/conditions-table.png
  modules/ROOT/images/dashboard.png
  modules/ROOT/images/metric-threshold.png
  modules/ROOT/images/notifications-notification-configure.png
  modules/ROOT/images/notifications-notification-edit.png
  modules/ROOT/images/notifications-page.png
  modules/ROOT/images/notifications-smtp-configure.png
  modules/ROOT/images/notifications-smtp-remove.png
  modules/ROOT/images/notifications-webhook-add.png
  modules/ROOT/images/notifications-webhook-remove.png
  modules/ROOT/pages/home-page/index.adoc
  modules/ROOT/pages/installation/server.adoc
  modules/ROOT/pages/monitoring/alerts-conditions.adoc
  modules/ROOT/pages/monitoring/concepts.adoc
  modules/ROOT/pages/monitoring/metric-manager.adoc
  modules/ROOT/pages/monitoring/notifications.adoc
Labels: documentation, cherry-picked

#111 remove Neo4j namespaces setting (#109)
  modules/ROOT/pages/addition/instance-requirements.adoc
Labels: documentation, cherry-picked

#112 remove dev from content branches
  publish.yml
Labels: documentation
