Repository neo4j/docs-ops-manager, pull requests merged in 2024-04, with the labels that each got.

#217 Add list of metrics reported by NOM
  modules/ROOT/pages/monitoring/metric-manager.adoc
Labels: cherry-pick-to-1.8, cherry-pick-to-1.9, cherry-pick-to-1.10

#219 Added the OpenSSL version requirement (#216)
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-picked

#220 Added the OpenSSL version requirement (#216)
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-picked

#221 Added the OpenSSL version requirement (#216)
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-picked

#222 1.8 cherry pick 217
  modules/ROOT/pages/monitoring/metric-manager.adoc
Labels: cherry-picked

#223 Add list of metrics reported by NOM (#217)
  modules/ROOT/pages/monitoring/metric-manager.adoc
Labels: cherry-picked

#224 Add list of metrics reported by NOM (#217)
  modules/ROOT/pages/monitoring/metric-manager.adoc
Labels: cherry-picked

#218 Document compatibility with java 21 additionally to java 17
  modules/ROOT/images/architecture.png
  modules/ROOT/pages/first-look/linux-first-look.adoc
  modules/ROOT/pages/installation/server.adoc
  modules/ROOT/pages/introduction/architecture.adoc
  modules/ROOT/pages/introduction/deployment.adoc
Labels: cherry-pick-to-1.9, cherry-pick-to-1.10

#228 update deployment center
  modules/ROOT/pages/addition/agent-installation/agent-install.adoc
  modules/ROOT/pages/first-look/linux-first-look.adoc
  modules/ROOT/pages/installation/kubernetes/helm-charts.adoc
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-pick-to-1.8, cherry-pick-to-1.9, cherry-pick-to-1.10

#229 update deployment center (#228)
  modules/ROOT/pages/addition/agent-installation/agent-install.adoc
  modules/ROOT/pages/first-look/linux-first-look.adoc
  modules/ROOT/pages/installation/kubernetes/helm-charts.adoc
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-picked

#230 update deployment center (#228)
  modules/ROOT/pages/addition/agent-installation/agent-install.adoc
  modules/ROOT/pages/first-look/linux-first-look.adoc
  modules/ROOT/pages/installation/kubernetes/helm-charts.adoc
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-picked

#231 update deployment center (#228)
  modules/ROOT/pages/addition/agent-installation/agent-install.adoc
  modules/ROOT/pages/first-look/linux-first-look.adoc
  modules/ROOT/pages/installation/kubernetes/helm-charts.adoc
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-picked
