Repository neo4j/docs-ops-manager, pull requests merged in 2024-03, with the labels that each got.

#195 Simplify the compatibility matrix
  modules/ROOT/pages/appendix/version-compatibility.adoc
Labels: cherry-pick-to-1.9

#191 Fix step order in docker first look guide
  modules/ROOT/pages/first-look/docker-first-look.adoc
  modules/ROOT/pages/installation/docker/compose.adoc
Labels: cherry-pick-to-1.8, cherry-pick-to-1.9

#203 Fix step order in docker first look guide (#191)
  modules/ROOT/pages/first-look/docker-first-look.adoc
  modules/ROOT/pages/installation/docker/compose.adoc
Labels: cherry-picked

#204 Fix step order in docker first look guide (#191)
  modules/ROOT/pages/first-look/docker-first-look.adoc
  modules/ROOT/pages/installation/docker/compose.adoc
Labels: cherry-picked

#205 Fix step order in docker first look guide (#191)
  modules/ROOT/pages/first-look/docker-first-look.adoc
  modules/ROOT/pages/installation/docker/compose.adoc
Labels: cherry-picked

#193 Update self-registration docs to reflect security changes
  modules/ROOT/pages/addition/agent-installation/self-registered.adoc
  modules/ROOT/pages/first-look/docker-first-look.adoc
  modules/ROOT/pages/installation/docker/compose.adoc
  modules/ROOT/pages/installation/docker/container.adoc
  modules/ROOT/pages/installation/kubernetes/helm-charts.adoc
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-pick-to-1.8, cherry-pick-to-1.9, cherry-pick-to-1.10

#206 Update self-registration docs to reflect security changes (#193)
  modules/ROOT/pages/addition/agent-installation/self-registered.adoc
  modules/ROOT/pages/first-look/docker-first-look.adoc
  modules/ROOT/pages/installation/docker/compose.adoc
  modules/ROOT/pages/installation/docker/container.adoc
  modules/ROOT/pages/installation/kubernetes/helm-charts.adoc
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-picked

#207 Update self-registration docs to reflect security changes (#193)
  modules/ROOT/pages/addition/agent-installation/self-registered.adoc
  modules/ROOT/pages/first-look/docker-first-look.adoc
  modules/ROOT/pages/installation/docker/compose.adoc
  modules/ROOT/pages/installation/docker/container.adoc
  modules/ROOT/pages/installation/kubernetes/helm-charts.adoc
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-picked

#208 Update self-registration docs to reflect security changes (#193)
  modules/ROOT/pages/addition/agent-installation/self-registered.adoc
  modules/ROOT/pages/first-look/docker-first-look.adoc
  modules/ROOT/pages/installation/docker/compose.adoc
  modules/ROOT/pages/installation/docker/container.adoc
  modules/ROOT/pages/installation/kubernetes/helm-charts.adoc
  modules/ROOT/pages/installation/server.adoc
Labels: cherry-picked

#212 fix bug in uri
  modules/ROOT/pages/first-look/linux-first-look.adoc
Labels: documentation, cherry-pick-to-1.8, cherry-pick-to-1.9, cherry-pick-to-1.10

#213 fix bug in uri (#212)
  modules/ROOT/pages/first-look/linux-first-look.adoc
Labels: cherry-picked

#215 fix bug in uri (#212)
  modules/ROOT/pages/first-look/linux-first-look.adoc
Labels: cherry-picked

#214 fix bug in uri (#212)
  modules/ROOT/pages/first-look/linux-first-look.adoc
Labels: cherry-picked
